name: Deploy site to gh-pages

on:
  push:
    branches:
      - "master"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install and test
        run: |
          npm install
          npm test

      - name: Build production site
        env:
          REMOTE_REPOSITORY: ${{ secrets.REMOTE_REPOSITORY }}
          REMOTE_REPOSITORY_BRANCH: ${{ secrets.REMOTE_REPOSITORY_BRANCH }}
        run: |
          yarn build:production

      - name: Deploy to gh-pages
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
          BUILD_DIR: public/
          EMAIL: ${{ secrets.EMAIL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}